export { default as HomePage } from "./HomePage"
export { default as FavouritePage } from "./FavouritePage"
export { default as RecipesByCategoryPage } from "./RecipesByCategoryPage"
export { default as RecipesByAreaPage } from "./RecipesByAreaPage"
export { default as RecipeDetailPage } from "./RecipeDetailPage"
